import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CountProvider from "@/utils/CountProvider";
import AuthProvider, { AuthContext } from "@/utils/AuthProvider";

import axios from "axios";

axios.defaults.baseURL = "https://ecommerce-c58p.vercel.app/";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <CountProvider>
            <Navbar/> 
            {children} 
            <Footer/> 
          </CountProvider>
        </AuthProvider>
        
      </body> 
    </html>
  );
}
